name: Pull latest MWI posts

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://medium.com/feed/@adrianmbond,https://api.allorigins.win/raw?url=https%3A%2F%2Fiambond.substack.com%2Ffeed"
          max_post_count: 5
          template: "- **[$title]($url)**<br/><sub>$description</sub><br/><br/>"
          disable_sort: false
